### ISSUE TITLE
Reading the csv file from Github repository 

### ISSUE THREAD

**Issue by doradu8030** [jbryer/DATA606Fall2017#9]
I am not able to upload data in R from GitHub, none of the following instructions work it gives different  error messages

could you please guide how to upload the data? 

smoking-UK <- read.csv(url("https://github.com/jbryer/DATA606Spring2017/tree/master/Data/Data from openintro.org/Ch 1 Exercise/smoking.csv"), header = FALSE)

x <- getURL("https://github.com/jbryer/DATA606Spring2017/tree/master/Data/Data from openintro.org/Ch 1 Exercise/smoking.csv")
y <- read.csv(text = x)

urlfile<-'https://github.com/jbryer/DATA606Spring2017/tree/master/Data/Data from openintro.org/Ch 1 Exercise/smoking.csv'
dsin<-read.csv(urlfile)

**Comment by jbryer** [comment]
First, I uploaded the data from OpenIntro to this repository here: https://github.com/jbryer/DATA606Fall2017/tree/master/Data

Second, when getting the URL to load into R, be sure to click the `Raw` button, otherwise R will try to load an HTML page and not the data file. For example, the following command will load the `smoking` dataset:

```
smoking <- read.csv('https://raw.githubusercontent.com/jbryer/DATA606Fall2017/master/Data/Data%20from%20openintro.org/Ch%201%20Exercise%20Data/smoking.csv')
```

Note that the domain is with `raw.githubusercontent.com`.
